In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib as jb

In [18]:
# read the data
data = pd.read_csv('first inten project.csv')
data.head(5)

Booking_ID  number of adults  number of children  number of weekend nights  \
0   INN00001                 1                   1                         2   
1   INN00002                 1                   0                         1   
2   INN00003                 2                   1                         1   
3   INN00004                 1                   0                         0   
4   INN00005                 1                   0                         1   

   number of week nights  type of meal  car parking space    room type  \
0                      5   Meal Plan 1                  0  Room_Type 1   
1                      3  Not Selected                  0  Room_Type 1   
2                      3   Meal Plan 1                  0  Room_Type 1   
3                      2   Meal Plan 1                  0  Room_Type 1   
4                      2  Not Selected                  0  Room_Type 1   

   lead time market segment type  repeated  P-C  P-not-C  average price   \
0        224             Offline         0    0        0           88.00   
1          5              Online         0    0        0          106.68   
2          1              Online         0    0        0           50.00   
3        211              Online         0    0        0          100.00   
4         48              Online         0    0        0           77.00   

   special requests date of reservation booking status  Unnamed: 17  
0                 0           10/2/2015   Not_Canceled          1.0  
1                 1           11/6/2018   Not_Canceled          NaN  
2                 0           2/28/2018       Canceled          NaN  
3                 1           5/20/2017       Canceled          NaN  
4                 0           4/11/2018       Canceled          NaN

In [19]:
data.info(), data.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36285 entries, 0 to 36284
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Booking_ID                36285 non-null  object 
 1   number of adults          36285 non-null  int64  
 2   number of children        36285 non-null  int64  
 3   number of weekend nights  36285 non-null  int64  
 4   number of week nights     36285 non-null  int64  
 5   type of meal              36285 non-null  object 
 6   car parking space         36285 non-null  int64  
 7   room type                 36285 non-null  object 
 8   lead time                 36285 non-null  int64  
 9   market segment type       36285 non-null  object 
 10  repeated                  36285 non-null  int64  
 11  P-C                       36285 non-null  int64  
 12  P-not-C                   36285 non-null  int64  
 13  average price             36285 non-null  float64
 14  specia

(None, (36285, 18))

In [20]:
data.drop(['Unnamed: 17', 'Booking_ID'], axis= 1, inplace= True)
data.head(5)

number of adults  number of children  number of weekend nights  \
0                 1                   1                         2   
1                 1                   0                         1   
2                 2                   1                         1   
3                 1                   0                         0   
4                 1                   0                         1   

   number of week nights  type of meal  car parking space    room type  \
0                      5   Meal Plan 1                  0  Room_Type 1   
1                      3  Not Selected                  0  Room_Type 1   
2                      3   Meal Plan 1                  0  Room_Type 1   
3                      2   Meal Plan 1                  0  Room_Type 1   
4                      2  Not Selected                  0  Room_Type 1   

   lead time market segment type  repeated  P-C  P-not-C  average price   \
0        224             Offline         0    0        0           88.00   
1          5              Online         0    0        0          106.68   
2          1              Online         0    0        0           50.00   
3        211              Online         0    0        0          100.00   
4         48              Online         0    0        0           77.00   

   special requests date of reservation booking status  
0                 0           10/2/2015   Not_Canceled  
1                 1           11/6/2018   Not_Canceled  
2                 0           2/28/2018       Canceled  
3                 1           5/20/2017       Canceled  
4                 0           4/11/2018       Canceled

## Handling Labels


In [21]:
data.describe(include= [object])

type of meal    room type market segment type date of reservation  \
count         36285        36285               36285               36285   
unique            4            7                   5                 553   
top     Meal Plan 1  Room_Type 1              Online          10/13/2018   
freq          27842        28138               23221                 254   

       booking status  
count           36285  
unique              2  
top      Not_Canceled  
freq            24396

In [22]:
# convert date of reservation into date type
data['date of reservation'] = pd.to_datetime(data['date of reservation'], format='mixed', errors='coerce')
data['date of reservation'].isna().sum() # the null referes to 29-2-2018! 2018 is not a leap year.

37

In [23]:
# droping records with 29-2-2018 as it's not an actual date (plus most of the records with this date is not canceled which it doesn't make sense)
# there's another option to convert it into 28 instead! bs i'm gonna drop them
data.dropna(subset=['date of reservation'], inplace=True)
data['date of reservation'].isna().sum()

0

In [24]:
# split the date of reservation into month and day (to find if the month and the day has something to do with booking status)
data['month'] = data['date of reservation'].dt.month
data['day'] = data['date of reservation'].dt.day
data.drop('date of reservation', axis= 1, inplace= True)
data.head(5)

number of adults  number of children  number of weekend nights  \
0                 1                   1                         2   
1                 1                   0                         1   
2                 2                   1                         1   
3                 1                   0                         0   
4                 1                   0                         1   

   number of week nights  type of meal  car parking space    room type  \
0                      5   Meal Plan 1                  0  Room_Type 1   
1                      3  Not Selected                  0  Room_Type 1   
2                      3   Meal Plan 1                  0  Room_Type 1   
3                      2   Meal Plan 1                  0  Room_Type 1   
4                      2  Not Selected                  0  Room_Type 1   

   lead time market segment type  repeated  P-C  P-not-C  average price   \
0        224             Offline         0    0        0           88.00   
1          5              Online         0    0        0          106.68   
2          1              Online         0    0        0           50.00   
3        211              Online         0    0        0          100.00   
4         48              Online         0    0        0           77.00   

   special requests booking status  month  day  
0                 0   Not_Canceled     10    2  
1                 1   Not_Canceled     11    6  
2                 0       Canceled      2   28  
3                 1       Canceled      5   20  
4                 0       Canceled      4   11

In [25]:
import category_encoders as ce

In [26]:
print(f'''Market Segment Types: {data['market segment type'].unique()}.
\nRoom Types: {data['room type'].unique()}.
\nMeal Types {data['type of meal'].unique()}''')

Market Segment Types: ['Offline' 'Online' 'Corporate' 'Aviation' 'Complementary'].

Room Types: ['Room_Type 1' 'Room_Type 4' 'Room_Type 2' 'Room_Type 6' 'Room_Type 5'
 'Room_Type 7' 'Room_Type 3'].

Meal Types ['Meal Plan 1' 'Not Selected' 'Meal Plan 2' 'Meal Plan 3']


5 cat -> 3 col (1 0 1)
7 cat -> 3 col (1 1 1)
4 cat -> 3 col (1 0 0)


In [27]:
#encode lables
binary_encoder = ce.BinaryEncoder(cols=['market segment type', 'room type', 'type of meal'])
data = binary_encoder.fit_transform(data)

In [28]:
data.columns

Index(['number of adults', 'number of children', 'number of weekend nights',
       'number of week nights', 'type of meal_0', 'type of meal_1',
       'type of meal_2', 'car parking space', 'room type_0', 'room type_1',
       'room type_2', 'lead time', 'market segment type_0',
       'market segment type_1', 'market segment type_2', 'repeated', 'P-C',
       'P-not-C', 'average price ', 'special requests', 'booking status',
       'month', 'day'],
      dtype='object')

In [29]:
data['booking status'].value_counts()

booking status
Not_Canceled    24366
Canceled        11882
Name: count, dtype: int64

In [30]:
# label encoding for the target
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['booking status'] = le.fit_transform(data['booking status'])
data.head(5)


number of adults  number of children  number of weekend nights  \
0                 1                   1                         2   
1                 1                   0                         1   
2                 2                   1                         1   
3                 1                   0                         0   
4                 1                   0                         1   

   number of week nights  type of meal_0  type of meal_1  type of meal_2  \
0                      5               0               0               1   
1                      3               0               1               0   
2                      3               0               0               1   
3                      2               0               0               1   
4                      2               0               1               0   

   car parking space  room type_0  room type_1  ...  market segment type_1  \
0                  0            0            0  ...                      0   
1                  0            0            0  ...                      1   
2                  0            0            0  ...                      1   
3                  0            0            0  ...                      1   
4                  0            0            0  ...                      1   

   market segment type_2  repeated  P-C  P-not-C  average price   \
0                      1         0    0        0           88.00   
1                      0         0    0        0          106.68   
2                      0         0    0        0           50.00   
3                      0         0    0        0          100.00   
4                      0         0    0        0           77.00   

   special requests  booking status  month  day  
0                 0               1     10    2  
1                 1               1     11    6  
2                 0               0      2   28  
3                 1               0      5   20  
4                 0               0      4   11  

[5 rows x 23 columns]

## Handling Numericals


In [31]:
cat = ['type of meal_0', 'type of meal_1', 'type of meal_2', 'room type_0', 'room type_1', 'room type_2', 'market segment type_0',
   'market segment type_1', 'market segment type_2', 'booking status', 'repeated', 'car parking space']

In [32]:
numerical_col = [col for col in data.columns if col not in cat]
data[numerical_col].describe()


number of adults  number of children  number of weekend nights  \
count      36248.000000        36248.000000              36248.000000   
mean           1.845178            0.105302                  0.810445   
std            0.518671            0.402597                  0.870938   
min            0.000000            0.000000                  0.000000   
25%            2.000000            0.000000                  0.000000   
50%            2.000000            0.000000                  1.000000   
75%            2.000000            0.000000                  2.000000   
max            4.000000           10.000000                  7.000000   

       number of week nights     lead time           P-C       P-not-C  \
count           36248.000000  36248.000000  36248.000000  36248.000000   
mean                2.204508     85.282360      0.023339      0.152919   
std                 1.410825     85.961536      0.368432      1.753126   
min                 0.000000      0.000000      0.000000      0.000000   
25%                 1.000000     17.000000      0.000000      0.000000   
50%                 2.000000     57.000000      0.000000      0.000000   
75%                 3.000000    126.000000      0.000000      0.000000   
max                17.000000    443.000000     13.000000     58.000000   

       average price   special requests         month           day  
count    36248.000000      36248.000000  36248.000000  36248.000000  
mean       103.435350          0.620034      7.429348     15.583011  
std         35.081308          0.786429      3.066604      8.734280  
min          0.000000          0.000000      1.000000      1.000000  
25%         80.300000          0.000000      5.000000      8.000000  
50%         99.450000          0.000000      8.000000     16.000000  
75%        120.000000          1.000000     10.000000     23.000000  
max        540.000000          5.000000     12.000000     31.000000

In [33]:
numerical_col

['number of adults',
 'number of children',
 'number of weekend nights',
 'number of week nights',
 'lead time',
 'P-C',
 'P-not-C',
 'average price ',
 'special requests',
 'month',
 'day']

In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

data[numerical_col] = scaler.fit_transform(data[numerical_col])


# Train the model

In [35]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [36]:
X = data.drop('booking status', axis= 1)
y = data['booking status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
# Logistic Regression
# -- Train
logreg_param_grid = [
    {'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2'], 'max_iter': [50, 150, 300, 500, 1000]},
]

logreg = LogisticRegression(solver= 'liblinear', random_state = 42)
logreg_grid = GridSearchCV(logreg, logreg_param_grid, cv=5, verbose=1, n_jobs=-1)
logreg_grid.fit(X_train, y_train)

print("Best parameters for Logistic Regression:", logreg_grid.best_params_)

# -- Test
y_pred_logreg = logreg_grid.predict(X_test)
accuracy_logreg = accuracy_score(y_test, y_pred_logreg)
print("Logistic Regression Accuracy:", accuracy_logreg)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_logreg))
print("Classification Report:\n", classification_report(y_test, y_pred_logreg))


Fitting 5 folds for each of 50 candidates, totalling 250 fits
Best parameters for Logistic Regression: {'C': 10, 'max_iter': 50, 'penalty': 'l1'}
Logistic Regression Accuracy: 0.8045517241379311
Confusion Matrix:
 [[1458  911]
 [ 506 4375]]
Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.62      0.67      2369
           1       0.83      0.90      0.86      4881

    accuracy                           0.80      7250
   macro avg       0.79      0.76      0.77      7250
weighted avg       0.80      0.80      0.80      7250



In [38]:
# KNN
# -- Train
knn_param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
}
knn = KNeighborsClassifier()
knn_grid = GridSearchCV(knn, knn_param_grid, cv=5, verbose=1, n_jobs=-1)
knn_grid.fit(X_train, y_train)

print("Best parameters for KNN:", knn_grid.best_params_)

# -- Test
y_pred_knn = knn_grid.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print("KNN Accuracy:", accuracy_knn)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("Classification Report:\n", classification_report(y_test, y_pred_knn))


Fitting 5 folds for each of 5 candidates, totalling 25 fits


Best parameters for KNN: {'n_neighbors': 5}
KNN Accuracy: 0.8453793103448276
Confusion Matrix:
 [[1764  605]
 [ 516 4365]]
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.74      0.76      2369
           1       0.88      0.89      0.89      4881

    accuracy                           0.85      7250
   macro avg       0.83      0.82      0.82      7250
weighted avg       0.84      0.85      0.84      7250



In [39]:
# Decision Tree
# -- Train
dtree_param_grid = {
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
}
dtree = DecisionTreeClassifier(random_state = 42)
dtree_grid = GridSearchCV(dtree, dtree_param_grid, cv=5, verbose=1, n_jobs=-1)
dtree_grid.fit(X_train, y_train)

print("Best parameters for Decision Tree:", dtree_grid.best_params_)

# -- Test
y_pred_dtree = dtree_grid.predict(X_test)
accuracy_dtree = accuracy_score(y_test, y_pred_dtree)
print("Decision Tree Accuracy:", accuracy_dtree)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dtree))
print("Classification Report:\n", classification_report(y_test, y_pred_dtree))


Fitting 5 folds for each of 12 candidates, totalling 60 fits
Best parameters for Decision Tree: {'max_depth': 10, 'min_samples_split': 5}
Decision Tree Accuracy: 0.8691034482758621
Confusion Matrix:
 [[1853  516]
 [ 433 4448]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.78      0.80      2369
           1       0.90      0.91      0.90      4881

    accuracy                           0.87      7250
   macro avg       0.85      0.85      0.85      7250
weighted avg       0.87      0.87      0.87      7250



In [40]:
# Random Forest
# -- Train
rf_param_grid = {
    'n_estimators': [10, 50, 100, 150, 300],
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    }
rf = RandomForestClassifier(random_state=42)
rf_grid = GridSearchCV(rf, rf_param_grid, cv=5, verbose=1, n_jobs=-1)
rf_grid.fit(X_train, y_train)

print("Best parameters for Random Forest:", rf_grid.best_params_)

# -- Test
y_pred_rf = rf_grid.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))


Fitting 5 folds for each of 60 candidates, totalling 300 fits
Best parameters for Random Forest: {'max_depth': None, 'min_samples_split': 5, 'n_estimators': 150}
Random Forest Accuracy: 0.900551724137931
Confusion Matrix:
 [[1895  474]
 [ 247 4634]]
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.80      0.84      2369
           1       0.91      0.95      0.93      4881

    accuracy                           0.90      7250
   macro avg       0.90      0.87      0.88      7250
weighted avg       0.90      0.90      0.90      7250

